/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 19/05/2022 20:22:07
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            25000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_PLLCLKFreq_Value                     84000000
#define MX_SYSCLKFreq_VALUE                     84000000
#define MX_HCLKFreq_Value                       84000000
#define MX_FCLKCortexFreq_Value                 84000000
#define MX_CortexFreq_Value                     84000000
#define MX_AHBFreq_Value                        84000000
#define MX_APB1Freq_Value                       42000000
#define MX_APB2Freq_Value                       84000000
#define MX_APB1TimFreq_Value                    84000000
#define MX_APB2TimFreq_Value                    84000000
#define MX_48MHZClocksFreq_Value                42000000
#define MX_EthernetFreq_Value                   16000000
#define MX_I2SClocksFreq_Value                  192000000
#define MX_RTCFreq_Value                        32000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    16000000

/*-------------------------------- DMA        --------------------------------*/

#define MX_DMA                                  1

/* NVIC Configuration */

/* NVIC DMA1_Stream3_IRQn */
#define MX_DMA1_Stream3_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream3_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream3_IRQn_Subriority         0

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- TIM4       --------------------------------*/

#define MX_TIM4                                 1

/* GPIO Configuration */

/* Pin PB7 */
#define MX_S_TIM4_CH2_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM4_CH2_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM4_CH2_Pin                       PB7
#define MX_S_TIM4_CH2_GPIOx                     GPIOB
#define MX_S_TIM4_CH2_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM4_CH2_GPIO_Pin                  GPIO_PIN_7
#define MX_S_TIM4_CH2_GPIO_AF                   GPIO_AF2_TIM4

/* DMA Configuration */

/* DMA TIM4_CH2 */
#define MX_TIM4_CH2_DMA_DMA_Handle
#define MX_TIM4_CH2_DMA_Instance                DMA1_Stream3
#define MX_TIM4_CH2_DMA_FIFOMode                DMA_FIFOMODE_DISABLE
#define MX_TIM4_CH2_DMA_Priority                DMA_PRIORITY_LOW
#define MX_TIM4_CH2_DMA_Channel                 DMA_CHANNEL_2
#define MX_TIM4_CH2_DMA_PeriphDataAlignment     DMA_PDATAALIGN_HALFWORD
#define MX_TIM4_CH2_DMA_MemDataAlignment        DMA_MDATAALIGN_HALFWORD
#define MX_TIM4_CH2_DMA_Mode                    DMA_NORMAL
#define MX_TIM4_CH2_DMA_Direction               DMA_MEMORY_TO_PERIPH
#define MX_TIM4_CH2_DMA_PeriphInc               DMA_PINC_DISABLE
#define MX_TIM4_CH2_DMA_MemInc                  DMA_MINC_ENABLE
#define MX_TIM4_CH2_DMA_IpInstance

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

#endif  /* __MX_DEVICE_H */

